### ISSUE TITLE
"pre-commit run" in the project directory runs the right hooks but in the wrong directory

### ISSUE THREAD

**Issue by dhandy2013** [ddanier/sub-pre-commit#1]
Thank you for creating sub-pre-commit! This is just what I was looking for, a simple Python-based solution for having a separate .pre-commit-config.yaml in each project sub-directory of a repository.

I set up my project according to the docs. Running "pre-commit run -a" in the root of the respository worked just fine. But running "pre-commit run -a" in a project-subdirectory chokes - the hooks are run with the current directory set not to the project sub-directory (even though that was the directory from which I ran pre-commit) but to the root of the repository. This was not expected.

I'm currently running pre-commit version 3.8.0:
```
$ pre-commit --version
pre-commit 3.8.0
```

Here are my .pre-commit-config.yaml files, slightly edited to remove irrelevant project details:

.pre-commit-config.yaml in root of repository:
```
repos:
  - repo: https://github.com/ddanier/sub-pre-commit.git
    rev: v3.8.0  # MUST match your pre-commit version
    hooks:
      - id: sub-pre-commit
        alias: my-project
        name: "pre-commit for my-project"
        args: ["-p", "my-project"]
        files: "^my-project/.*"
        stages: ["pre-commit"]
        minimum_pre_commit_version: '3.8.0'
```

.pre-commit-config.yaml in my-project project sub-directory:
```
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.11
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff check
        language: system
        pass_filenames: false
        require_serial: true
      - id: mypy
        name: mypy
        entry: poetry run mypy .
        language: system
        pass_filenames: false
        require_serial: true
```

Running pre-commit in the root of the repository:
```
$ pre-commit run -a
pre-commit for my-project................................................Passed
```

Running pre-commit in the my-project sub-directory:
```
$ pre-commit run -a
ruff.....................................................................Failed
- hook id: ruff
- exit code: 1

Poetry could not find a pyproject.toml file in /home/david/repos/my-repo or its parents

mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

Poetry could not find a pyproject.toml file in /home/david/repos-my-repo or its parents
```

Expected behavior is that it would pass either way. With some debugging I was able to figure out that the reason for the failure is that mypy and ruff were being run with the current directory set to the root of the repository, even though pre-commit was run from the my-project sub-directory instead.
